# https://travis-ci.com/phoebe-project/phoebe2-tables

# NOTE: because we checkout the branch, we may not be at this EXACT commit,
# but rather at the latest.  So re-running a travis build on and old commit
# will still update using the latest sources in the branch.  This shouldn't
# be a problem - we have the builds set to autocancel if a new push occurs
# anyways.

language: python
language: python
python:
  - "2.7"
  - "3.6"

os: linux
dist: trusty


script: |
  if [ "$TRAVIS_COMMIT_MESSAGE" != "TRAVIS: updating passband lists" ] && [ -n $GITHUB_API_KEY ]; then
    git checkout $TRAVIS_BRANCH
    git remote rm origin
    git remote add origin https://kecnry:${GITHUB_API_KEY}@github.com/phoebe-project/phoebe2-tables.git > /dev/null 2>&1
    git -c user.name='travis' -c user.email='travis'
    cd passbands
    pip install numpy;
    python update_list.py;
    git commit -a -m 'TRAVIS: updating passband lists'
    git push -q -f origin $TRAVIS_BRANCH > /dev/null 2>&1
  fi
